# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-06 01:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='blockedUsers',
            field=models.ManyToManyField(related_name='_user_blockedUsers_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
