# Generated by Django 2.2.13 on 2020-06-05 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190417_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='show_guide',
            field=models.BooleanField(default=True),
        ),
    ]
