# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-06 02:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_blockedusers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='blockedUsers',
        ),
        migrations.AddField(
            model_name='user',
            name='blocked_users',
            field=models.ManyToManyField(related_name='_user_blocked_users_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
