strictness: veryhigh
doc-warnings: true
test-warnings: true

ignore-paths:
  - mission_control/static/
  - mission_control/migrations/
  - rovercode_web/users/
  - rovercode_web/contrib/
  - config/
  - docs/
  - manage.py

pep8:
  full: true

pep257:
  run: true
  disable:
    # 1 blank line required before class docstring
    - D203
