sudo: true
before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq build-essential gettext python-dev zlib1g-dev libpq-dev
  xvfb
- sudo apt-get install -qq libtiff4-dev libjpeg8-dev libfreetype6-dev liblcms1-dev
  libwebp-dev
- sudo apt-get install -qq graphviz-dev python-setuptools python3-dev python-virtualenv
  python-pip
- sudo apt-get install -qq firefox automake libtool libreadline6 libreadline6-dev
  libreadline-dev
- sudo apt-get install -qq libsqlite3-dev libxml2 libxml2-dev libssl-dev libbz2-dev
  wget curl llvm
install:
- pip install pip==10.0.1
- pip install pipenv==11.10.1
- pip install coveralls
- pipenv install --dev
script:
- py.test --cov-report=
- prospector
- pushd docs
- make html
- popd
after_success:
- coveralls
language: python
python:
- '3.6'
deploy:
  - provider: codedeploy
    access_key_id: AKIAIIORSR4VN3YQY2YQ
    secret_access_key:
      secure: NDD69o8NxncxdsqxeEL574kqoQ27jiN0K0U53dUWnjLrl1SVOg+8WRITsyU5e9DS4hzFiKWO5qOkbnh9xoKLRO/sYRxUGOwW5ZKxqkXWHFpyL/uIs2KpzmXRcaJSs3iYmowrbniKI7awH31HIvPM6EbX2EsDlb89nb2C7FNUaAlt+HZ6cwSBJsMBoQPuEe7nw5TDjZBYBhWjFfuK+MJTXc3quB2msXuBsdwvobg0AvPHEWAQl5Yyamj182Zc0DveqEeB0HbBUU2eZDvZTJclL99iBQPGiUuXfU71j5e9dg0VlF+GqY85b9kkYjoFndMWLBqCDL3855KqRIg6ouqsJsvPCTD+s4f0DNvvqt4H30T56gq8IGMqS4WOWpIWFOg/g82H23MFhsrc1IwHkdxsfWwaw/IGq3fVqeahpFqQczViYdvEU0C+JOVHdKNxy8FxU7hvXB/fZSNlPy/1VniBQK6AmzP1uA/wOURG2Oo3l4jzGQ4y7A4k7wFZVSH43iZ5hKCqNcrP5skDeu43/prrCpO0E9XsjiuexCwU2cEeTAKVLrrzBNviKHPrYH8LjwZlAtioxNXSYcAvF7+z8/wLO4lHIGzU/Vi+A55vedhaFLHefWfTJW8i6LrPjTMURzsZ921ZQOKKj4q6Tfcfcl0XkSWQxPgx7qDr12ehw7Q9NZg=
    revision_type: github
    region: us-east-2
    application: alpha-rovercode-web
    deployment_group: alpha-rovercode-web
    on:
      repo: rovercode/rovercode-web
      branch: alpha
  - provider: codedeploy
    access_key_id: AKIAIIORSR4VN3YQY2YQ
    secret_access_key:
      secure: NDD69o8NxncxdsqxeEL574kqoQ27jiN0K0U53dUWnjLrl1SVOg+8WRITsyU5e9DS4hzFiKWO5qOkbnh9xoKLRO/sYRxUGOwW5ZKxqkXWHFpyL/uIs2KpzmXRcaJSs3iYmowrbniKI7awH31HIvPM6EbX2EsDlb89nb2C7FNUaAlt+HZ6cwSBJsMBoQPuEe7nw5TDjZBYBhWjFfuK+MJTXc3quB2msXuBsdwvobg0AvPHEWAQl5Yyamj182Zc0DveqEeB0HbBUU2eZDvZTJclL99iBQPGiUuXfU71j5e9dg0VlF+GqY85b9kkYjoFndMWLBqCDL3855KqRIg6ouqsJsvPCTD+s4f0DNvvqt4H30T56gq8IGMqS4WOWpIWFOg/g82H23MFhsrc1IwHkdxsfWwaw/IGq3fVqeahpFqQczViYdvEU0C+JOVHdKNxy8FxU7hvXB/fZSNlPy/1VniBQK6AmzP1uA/wOURG2Oo3l4jzGQ4y7A4k7wFZVSH43iZ5hKCqNcrP5skDeu43/prrCpO0E9XsjiuexCwU2cEeTAKVLrrzBNviKHPrYH8LjwZlAtioxNXSYcAvF7+z8/wLO4lHIGzU/Vi+A55vedhaFLHefWfTJW8i6LrPjTMURzsZ921ZQOKKj4q6Tfcfcl0XkSWQxPgx7qDr12ehw7Q9NZg=
    revision_type: github
    region: us-east-2
    application: beta-rovercode-web
    deployment_group: beta-rovercode-web
    on:
      repo: rovercode/rovercode-web
      branch: development
  - provider: codedeploy
    access_key_id: AKIAIIORSR4VN3YQY2YQ
    secret_access_key:
      secure: NDD69o8NxncxdsqxeEL574kqoQ27jiN0K0U53dUWnjLrl1SVOg+8WRITsyU5e9DS4hzFiKWO5qOkbnh9xoKLRO/sYRxUGOwW5ZKxqkXWHFpyL/uIs2KpzmXRcaJSs3iYmowrbniKI7awH31HIvPM6EbX2EsDlb89nb2C7FNUaAlt+HZ6cwSBJsMBoQPuEe7nw5TDjZBYBhWjFfuK+MJTXc3quB2msXuBsdwvobg0AvPHEWAQl5Yyamj182Zc0DveqEeB0HbBUU2eZDvZTJclL99iBQPGiUuXfU71j5e9dg0VlF+GqY85b9kkYjoFndMWLBqCDL3855KqRIg6ouqsJsvPCTD+s4f0DNvvqt4H30T56gq8IGMqS4WOWpIWFOg/g82H23MFhsrc1IwHkdxsfWwaw/IGq3fVqeahpFqQczViYdvEU0C+JOVHdKNxy8FxU7hvXB/fZSNlPy/1VniBQK6AmzP1uA/wOURG2Oo3l4jzGQ4y7A4k7wFZVSH43iZ5hKCqNcrP5skDeu43/prrCpO0E9XsjiuexCwU2cEeTAKVLrrzBNviKHPrYH8LjwZlAtioxNXSYcAvF7+z8/wLO4lHIGzU/Vi+A55vedhaFLHefWfTJW8i6LrPjTMURzsZ921ZQOKKj4q6Tfcfcl0XkSWQxPgx7qDr12ehw7Q9NZg=
    revision_type: github
    region: us-east-2
    application: rovercode-web
    deployment_group: rovercode-web
    on:
      repo: rovercode/rovercode-web
      branch: master
  - provider: s3
    access_key_id: AKIAIIORSR4VN3YQY2YQ
    secret_access_key:
      secure: NDD69o8NxncxdsqxeEL574kqoQ27jiN0K0U53dUWnjLrl1SVOg+8WRITsyU5e9DS4hzFiKWO5qOkbnh9xoKLRO/sYRxUGOwW5ZKxqkXWHFpyL/uIs2KpzmXRcaJSs3iYmowrbniKI7awH31HIvPM6EbX2EsDlb89nb2C7FNUaAlt+HZ6cwSBJsMBoQPuEe7nw5TDjZBYBhWjFfuK+MJTXc3quB2msXuBsdwvobg0AvPHEWAQl5Yyamj182Zc0DveqEeB0HbBUU2eZDvZTJclL99iBQPGiUuXfU71j5e9dg0VlF+GqY85b9kkYjoFndMWLBqCDL3855KqRIg6ouqsJsvPCTD+s4f0DNvvqt4H30T56gq8IGMqS4WOWpIWFOg/g82H23MFhsrc1IwHkdxsfWwaw/IGq3fVqeahpFqQczViYdvEU0C+JOVHdKNxy8FxU7hvXB/fZSNlPy/1VniBQK6AmzP1uA/wOURG2Oo3l4jzGQ4y7A4k7wFZVSH43iZ5hKCqNcrP5skDeu43/prrCpO0E9XsjiuexCwU2cEeTAKVLrrzBNviKHPrYH8LjwZlAtioxNXSYcAvF7+z8/wLO4lHIGzU/Vi+A55vedhaFLHefWfTJW8i6LrPjTMURzsZ921ZQOKKj4q6Tfcfcl0XkSWQxPgx7qDr12ehw7Q9NZg=
    bucket: rovercode-contrib-docs
    local_dir: docs/_build/html
    upload-dir: rovercode-web/development
    acl: public_read
    skip_cleanup: true
    region: us-east-2
    on:
      repo: rovercode/rovercode-web
      branch: development
  - provider: s3
    access_key_id: AKIAIIORSR4VN3YQY2YQ 
    secret_access_key:
      secure: NDD69o8NxncxdsqxeEL574kqoQ27jiN0K0U53dUWnjLrl1SVOg+8WRITsyU5e9DS4hzFiKWO5qOkbnh9xoKLRO/sYRxUGOwW5ZKxqkXWHFpyL/uIs2KpzmXRcaJSs3iYmowrbniKI7awH31HIvPM6EbX2EsDlb89nb2C7FNUaAlt+HZ6cwSBJsMBoQPuEe7nw5TDjZBYBhWjFfuK+MJTXc3quB2msXuBsdwvobg0AvPHEWAQl5Yyamj182Zc0DveqEeB0HbBUU2eZDvZTJclL99iBQPGiUuXfU71j5e9dg0VlF+GqY85b9kkYjoFndMWLBqCDL3855KqRIg6ouqsJsvPCTD+s4f0DNvvqt4H30T56gq8IGMqS4WOWpIWFOg/g82H23MFhsrc1IwHkdxsfWwaw/IGq3fVqeahpFqQczViYdvEU0C+JOVHdKNxy8FxU7hvXB/fZSNlPy/1VniBQK6AmzP1uA/wOURG2Oo3l4jzGQ4y7A4k7wFZVSH43iZ5hKCqNcrP5skDeu43/prrCpO0E9XsjiuexCwU2cEeTAKVLrrzBNviKHPrYH8LjwZlAtioxNXSYcAvF7+z8/wLO4lHIGzU/Vi+A55vedhaFLHefWfTJW8i6LrPjTMURzsZ921ZQOKKj4q6Tfcfcl0XkSWQxPgx7qDr12ehw7Q9NZg=
    bucket: rovercode-contrib-docs
    local_dir: docs/_build/html
    upload-dir: rovercode-web/master
    acl: public_read
    skip_cleanup: true
    region: us-east-2
    on:
      repo: rovercode/rovercode-web
      branch: master
notifications:
  slack:
    secure: lGfSdmE+gADEOsBsS1tu1jFkhrGqpAZlIUMMXFYjCPODfwrkTC9onyimKzUYOzDcEvOVP4uNQo5XFIZD5/dOg/Grjav9THvwADLuAumkMk9iH4tetWQ1KBRMawTxmMHUQa7ujoOERuEttrq4FhDo84RNaK8d+eLO8iuhHDGeqTd4MSgAak1aukCiohRKfvgNBNAlPPaiBKbeuSea+j46pRqhC/FM55cpIV9iiH0AhFIC9HKa3UkhHfNXh7fybTQuVVD0r+SOCbnJxQvIOzwjWQco+HjZXgXn62GSFLX4bW2WmqfFKuTiLhzXuLKXr5ZI6ggBlqaANvqCsv4Ki8yQ9/qsQOVUipZAnFzvMCAL1XGIBJdRO9mzBegzDk/QO538jOcPzK2P24abEvESqgC3Ld4JOcv1H6ZJ8dFVxnbCPcZIhgE6HoGD+8YHyFoZ5MvR6xq0cQfd7lmXPDgiYXnoQXwsx1Zd95hH07P+BQlsCFfhyG/T0QuXg6XIE7c5NdbZoZutxAbjPjOCJMWNRQlp20PWD+ms9QUNTvtcwtOsubobtoDi0mDSLK/RB6gvUEJkYSh6zmKoIYGLooXSeE8VnZ82V3RgzGnvNPSI8qpd+44czgpRcFtnATdmTw+zrxSywCCXhl9OODB2M4cxvZ7Vfgz2EQfb4taOxH8LibYEyQQ=
