# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 04:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mission_control', '0002_rover_local_ip'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockDiagram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('content', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='rover',
            name='last_checkin',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
