# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-29 02:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission_control', '0003_auto_20170212_0419'),
    ]

    operations = [
        migrations.AddField(
            model_name='rover',
            name='left_backward_pin',
            field=models.TextField(default='XIO-P1'),
        ),
        migrations.AddField(
            model_name='rover',
            name='left_eye_pin',
            field=models.TextField(default='XIO-P2'),
        ),
        migrations.AddField(
            model_name='rover',
            name='left_forward_pin',
            field=models.TextField(default='XIO-P0'),
        ),
        migrations.AddField(
            model_name='rover',
            name='right_backward_pin',
            field=models.TextField(default='XIO-P7'),
        ),
        migrations.AddField(
            model_name='rover',
            name='right_eye_pin',
            field=models.TextField(default='XIO-P4'),
        ),
        migrations.AddField(
            model_name='rover',
            name='right_forward_pin',
            field=models.TextField(default='XIO-P6'),
        ),
    ]
