# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-30 01:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mission_control', '0004_auto_20170529_0228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rover',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
