# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-05 02:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission_control', '0005_auto_20170530_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rover',
            name='left_backward_pin',
            field=models.CharField(default='XIO-P1', max_length=25),
        ),
        migrations.AlterField(
            model_name='rover',
            name='left_eye_pin',
            field=models.CharField(default='XIO-P2', max_length=25),
        ),
        migrations.AlterField(
            model_name='rover',
            name='left_forward_pin',
            field=models.CharField(default='XIO-P0', max_length=25),
        ),
        migrations.AlterField(
            model_name='rover',
            name='right_backward_pin',
            field=models.CharField(default='XIO-P7', max_length=25),
        ),
        migrations.AlterField(
            model_name='rover',
            name='right_eye_pin',
            field=models.CharField(default='XIO-P4', max_length=25),
        ),
        migrations.AlterField(
            model_name='rover',
            name='right_forward_pin',
            field=models.CharField(default='XIO-P6', max_length=25),
        ),
    ]
