# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-17 01:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mission_control', '0008_auto_20170605_0242'),
    ]

    operations = []
