# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-08 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('mission_control', '0010_auto_20180408_1440'), ('mission_control', '0011_auto_20180408_1446')]

    dependencies = [
        ('mission_control', '0009_rover_oauth_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='rover',
            name='left_eye_i2c_addr',
            field=models.IntegerField(blank=True, default=19),
        ),
        migrations.AddField(
            model_name='rover',
            name='left_eye_i2c_port',
            field=models.IntegerField(blank=True, default=2),
        ),
        migrations.AddField(
            model_name='rover',
            name='right_eye_i2c_addr',
            field=models.IntegerField(blank=True, default=19),
        ),
        migrations.AddField(
            model_name='rover',
            name='right_eye_i2c_port',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='rover',
            name='left_eye_pin',
            field=models.CharField(default='XIO-P2', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='rover',
            name='right_eye_pin',
            field=models.CharField(default='XIO-P4', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='rover',
            name='left_eye_pin',
            field=models.CharField(blank=True, default='XIO-P2', max_length=25),
        ),
        migrations.AlterField(
            model_name='rover',
            name='right_eye_pin',
            field=models.CharField(blank=True, default='XIO-P4', max_length=25),
        ),
    ]
