# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-13 14:14
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mission_control', '0011_auto_20190129_0521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rover',
            name='left_backward_pin',
        ),
        migrations.RemoveField(
            model_name='rover',
            name='left_eye_i2c_addr',
        ),
        migrations.RemoveField(
            model_name='rover',
            name='left_eye_i2c_port',
        ),
        migrations.RemoveField(
            model_name='rover',
            name='left_eye_pin',
        ),
        migrations.RemoveField(
            model_name='rover',
            name='left_forward_pin',
        ),
        migrations.RemoveField(
            model_name='rover',
            name='right_backward_pin',
        ),
        migrations.RemoveField(
            model_name='rover',
            name='right_eye_i2c_addr',
        ),
        migrations.RemoveField(
            model_name='rover',
            name='right_eye_i2c_port',
        ),
        migrations.RemoveField(
            model_name='rover',
            name='right_eye_pin',
        ),
        migrations.RemoveField(
            model_name='rover',
            name='right_forward_pin',
        ),
        migrations.AddField(
            model_name='rover',
            name='config',
            field=django.contrib.postgres.fields.jsonb.JSONField(default='{"left_eye_port": 1, "right_eye_port": 2, "left_motor_port": 3, "right_motor_port": 4}'),
        ),
    ]
