# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-31 20:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mission_control', '0011_auto_20190129_0521'),
    ]

    operations = [
        migrations.AddField(
            model_name='rover',
            name='shared_users',
            field=models.ManyToManyField(related_name='_rover_shared_users_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
