# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-31 20:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission_control', '0012_rover_shared_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rover',
            name='shared_users',
            field=models.ManyToManyField(null=True, related_name='_rover_shared_users_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
