# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-31 22:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission_control', '0014_auto_20190131_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rover',
            name='shared_users',
            field=models.ManyToManyField(blank=True, related_name='shared_rover', to=settings.AUTH_USER_MODEL),
        ),
    ]
