# Generated by Django 2.2.3 on 2019-08-01 01:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mission_control', '0015_rover_shared_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rover',
            name='oauth_application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.OAUTH2_PROVIDER_APPLICATION_MODEL),
        ),
    ]
