# Generated by Django 2.2.3 on 2019-08-01 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mission_control', '0015_rover_shared_users'),
    ]

    operations = []
