# Generated by Django 2.2.4 on 2019-08-11 20:04

import django.contrib.postgres.fields.citext
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mission_control', '0017_auto_20190811_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=django.contrib.postgres.fields.citext.CICharField(max_length=30, unique=True),
        ),
    ]
