# Generated by Django 2.2.10 on 2020-02-25 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission_control', '0018_auto_20190811_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockdiagram',
            name='flagged',
            field=models.BooleanField(default=False),
        ),
    ]
