# Generated by Django 2.2.11 on 2020-03-30 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mission_control', '0019_blockdiagram_flagged'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rover',
        ),
    ]
