# Generated by Django 2.2.11 on 2020-04-24 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0001_initial'),
        ('mission_control', '0020_delete_rover'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockdiagram',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blockdiagram',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='block_diagrams', to='curriculum.Lesson'),
        ),
        migrations.AddField(
            model_name='blockdiagram',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='curriculum.State'),
        ),
    ]
