# Generated by Django 2.2.18 on 2021-03-05 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mission_control', '0021_auto_20200424_1854'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockDiagramBlogQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required', models.BooleanField(default=False)),
                ('block_diagram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_questions', to='mission_control.BlockDiagram')),
            ],
        ),
        migrations.CreateModel(
            name='BlogQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='BlogAnswer',
            fields=[
                ('block_diagram_blog_question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='blog_answer', serialize=False, to='mission_control.BlockDiagramBlogQuestion')),
                ('answer', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='blockdiagramblogquestion',
            name='blog_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mission_control.BlogQuestion'),
        ),
        migrations.AddConstraint(
            model_name='blockdiagramblogquestion',
            constraint=models.UniqueConstraint(fields=('block_diagram', 'blog_question'), name='unique_bd_blog_question'),
        ),
    ]
