# Generated by Django 2.2.18 on 2021-03-07 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission_control', '0022_auto_20210305_0333'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockdiagramblogquestion',
            name='sequence_number',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
