# Generated by Django 2.2.18 on 2021-03-20 19:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mission_control', '0023_blockdiagramblogquestion_sequence_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockdiagram',
            name='share_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Private'), (2, 'Public'), (3, 'Cohort'), (4, 'Users')], default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blockdiagram',
            name='share_users',
            field=models.ManyToManyField(blank=True, related_name='shared_block_diagrams', to=settings.AUTH_USER_MODEL),
        ),
    ]
