# Generated by Django 2.2.18 on 2021-03-20 19:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mission_control', '0025_auto_20210320_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockdiagram',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='block_diagrams', to=settings.AUTH_USER_MODEL),
        ),
    ]
