# Generated by Django 2.2.18 on 2021-03-22 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission_control', '0026_auto_20210320_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockdiagram',
            name='share_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Private'), (2, 'Public'), (3, 'Cohort')], default=1),
        ),
    ]
