# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-14 18:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=25)),
                ('body', models.CharField(max_length=2000)),
                ('experience_level', models.CharField(max_length=25)),
                ('category', models.CharField(max_length=25)),
                ('creation_time', models.DateTimeField(auto_now=True)),
                ('in_progress', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
