# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-14 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_auto_20181014_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportrequest',
            name='category',
            field=models.CharField(choices=[('DEBUG', 'DEBUG'), ('WHAT_NEXT', 'WHAT_NEXT'), ('FUN_IDEAS', 'FUN_IDEAS')], max_length=25),
        ),
    ]
