# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-21 14:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mission_control', '0010_add_i2c_eyes'),
        ('support', '0003_auto_20181014_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportrequest',
            name='program',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mission_control.BlockDiagram'),
            preserve_default=False,
        ),
    ]
