# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-11 18:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('support', '0004_supportrequest_program'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbuseReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transcript', models.CharField(max_length=100000)),
                ('accused_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accused_user', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reporter', to=settings.AUTH_USER_MODEL)),
                ('support_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='support.SupportRequest')),
            ],
        ),
    ]
