# Generated by Django 2.2.11 on 2020-04-24 18:54

import curriculum.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mission_control', '0020_delete_rover'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.SmallIntegerField(choices=[(1, 'AVAILABLE'), (2, 'UNAVAILABLE'), (3, 'IN_PROGRESS'), (4, 'COMPLETE')], default=curriculum.models.ProgressState(1))),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_number', models.PositiveSmallIntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='curriculum.Course')),
                ('reference', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reference_of', to='mission_control.BlockDiagram')),
            ],
        ),
    ]
