# Generated by Django 2.2.14 on 2020-08-01 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_auto_20200608_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='tier',
            field=models.PositiveSmallIntegerField(default=2),
        ),
    ]
