# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-22 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='dummy', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
